[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.bdist_wheel]
python_tag = "py35.py36.py37.py38.py312"

[tool.aliases]
test = "pytest"

[tool.flake8]
exclude = ".git,.env/*,docs/*,build/*,.eggs/*,*.egg-info/*,.tox"
max-line-length = 120

[project]
name = "conformity"
dynamic = ["version"]
description = "Cacheable schema description and validation"
readme = "README.rst"
authors = [
    {name = "Eventbrite, Inc.", email = "opensource@eventbrite.com"}
]
license = {text = "Apache 2.0", files = ["LICENSE"]}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development",
]
requires-python = ">=3.5"
dependencies = [
    "attrs>=17.4,<24",
    "six",
]

[project.urls]
Documentation = "https://conformity.readthedocs.io"
Issues = "https://github.com/eventbrite/conformity/issues"
CI = "https://travis-ci.org/eventbrite/conformity/"

[project.optional-dependencies]
currency = ["currint"]
country = ["pycountry>=19.7.15"]
sphinx = [
    "sphinx~=3.5; python_version >= '3.6' and python_version < '3.12'",
    "sphinx~=7.2; python_version >= '3.12'",
    "jinja2==3.0.3; python_version >= '3.6' and python_version < '3.12'",
    "jinja2>=3.1.2; python_version >= '3.12'",
]
docs = [
    "sphinx~=3.5; python_version >= '3.6' and python_version < '3.12'",
    "sphinx~=7.2; python_version >= '3.12'", 
    "jinja2==3.0.3; python_version >= '3.6' and python_version < '3.12'",
    "jinja2>=3.1.2; python_version >= '3.12'",
    "pycountry>=19.7.15",
    "currint",
]
testing = [
    "freezegun==1.0.0",
    "mypy~=0.740; python_version < '3.12'",
    "mypy>=1.5.1; python_version >= '3.12'",
    "pytest>4.2,<5.4; python_version < '3.12'",
    "pytest>=7.4.0; python_version >= '3.12'",
    "pytest-cov~=2.5; python_version < '3.12'",
    "pytest-cov>=4.1.0; python_version >= '3.12'",
    "coverage~=5.2; python_version < '3.12'",
    "coverage>=7.2.7; python_version >= '3.12'",
    "pytest-runner",
    "pytz",
    "importlib-metadata~=5.0; python_version < '3.12'",
    "importlib-metadata>=6.8.0; python_version >= '3.12'",
    "currint",
    "pycountry>=19.7.15",
]
mypy = [
    "types-six; python_version >= '3.7'",
    "types-pytz; python_version >= '3.7'",
]

[tool.setuptools]
package-dir = {"" = "."}
packages = ["conformity", "conformity.fields", "conformity.settings", "conformity.sphinx_ext"]
include-package-data = true
zip-safe = false

[tool.setuptools.dynamic]
version = {attr = "conformity.__version__"}

[tool.setuptools.package-data]
conformity = ["py.typed"]
"conformity.sphinx_ext" = ["static/*"]

[tool.pytest.ini_options]
junit_family = "xunit2"
addopts = "-s --junitxml=pytests.xml --cov-fail-under=85 --cov-branch --cov-report=term-missing --cov=conformity"
filterwarnings = [
    "ignore::DeprecationWarning:jinja2.utils",
    "ignore::DeprecationWarning:jinja2.runtime"
]

[tool.mypy]
python_version = "3.12"
check_untyped_defs = true

[[tool.mypy.overrides]]
module = "conftest"
ignore_errors = true

[[tool.mypy.overrides]]
module = "setup"
ignore_errors = true

[[tool.mypy.overrides]]
module = "tasks"
ignore_errors = true

[[tool.mypy.overrides]]
module = "currint.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "freezegun.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pycountry.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pytest.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "sphinx.*"
ignore_missing_imports = true

[tool.isort]
multi_line_output = 3
line_length = 120
include_trailing_comma = true
combine_as_imports = true
force_grid_wrap = 2
use_parentheses = true
force_sort_within_sections = true
lines_after_imports = 2
skip_glob = ["*.git/*", "*.env/*", "*/docs/*", "*/build/*", "*/.eggs/*", "*.egg-info/*", ".tox"]
not_skip = "__init__.py"
add_imports = ["__future__.absolute_import", "__future__.unicode_literals"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "CURRENT_PROJECT", "LOCALFOLDER", "TESTS"]
no_lines_before = ["LOCALFOLDER"]
known_third_party = ["attr", "currint", "dateutil", "freezegun", "py", "pycountry", "pytest", "pytz", "six"]
known_current_project = ["conformity"]
known_tests = ["tests"]
