from __future__ import (
    absolute_import,
    unicode_literals,
)


# Error codes
ERROR_CODE_INVALID = 'INVALID'
ERROR_CODE_MISSING = 'MISSING'
ERROR_CODE_UNKNOWN = 'UNKNOWN'


# Warning codes
WARNING_CODE_FIELD_DEPRECATED = 'FIELD_DEPRECATED'
WARNING_CODE_FIELD_DEPRECATED_REMOVED = 'FIELD_DEPRECATED_REMOVED'
WARNING_CODE_FIELD_DEPRECATED_RENAMED = 'FIELD_DEPRECATED_RENAMED'
WARNING_CODE_WARNING = 'WARNING'
